### ISSUE TITLE
Problem using gsl::owner<T> with MSVC12

### ISSUE THREAD

**Issue by sg-james** [martinmoene/gsl-lite#111]
This fails to compile with msvc12 

```c++
gsl::owner<int*> new_int()
{
    gsl::owner<int*> result = new int(1);
    return result;
}

int main(int argc, char* argv[])
{
   gsl::owner<int*> tmp = new_int();
}
```

Error:
```cpp
C:\...\.cpp(10) : error C2440: 'initializing' : cannot convert from 'int *' to 'gsl::owner<int *>'
        No constructor could take the source type, or constructor overload resolution was ambiguous
C:\...\.cpp(41) : error C2100: illegal indirection
C:\...\.cpp(41) : error C2088: '<<' : illegal for class
```

Research:

`__cplusplus` : 199711  ( not properly defined 2011.. b/c not feature complete?)
`_MSVC_LANG` : 0  ( not defined until MSVC14?)
`#define gsl_HAVE_ALIAS_TEMPLATE       gsl_CPP11_14` : 0

According to this link: https://msdn.microsoft.com/en-us/library/hh567368.aspx
Alias templates support is available in MSVC 2013 ( MSVC12)
`gsl_CPP11_14` restricts usage to MSVC14.

Changing to `gsl_CPP11_12` allows it to work, perhaps that is a solution.

**Comment by martinmoene** [comment]
@sg-james Thanks for your clear report. The `gsl::owner<>` alias template should now also work with VC12 (Visual Studio 2013).
