### ISSUE TITLE
Use std::byte if available

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/gsl-lite#120]
Select std::byte or gsl::byte

`-Dgsl_CONFIG_SELECT_BYTE=gsl_BYTE_DEFAULT` / `gsl_BYTE_GSL` /  `gsl_BYTE_STD`

Plan:
- [ ] Readme
- [ ] gsl-lite.hpp

**Comment by mbeutel** [comment]
For the reasons explained in #121, I'd rather not introduce a `gsl_CONFIG_SELECT_BYTE` option.
