### ISSUE TITLE
Unused parameter in trivial span constructor with contract level off

### ISSUE THREAD

**Issue by kugelrund** [martinmoene/gsl-lite#123]
Compiling the code
```c++
#include "gsl.hpp"

int main()
{
    gsl::span<double> test(nullptr, 0);
}
```
with `g++ -std=c++11 -Dgsl_CONFIG_CONTRACT_LEVEL_OFF -Werror=unused-parameter test.cpp` fails due to the `size_in` parameter only being used in an `Expects` in this constructor: https://github.com/martinmoene/gsl-lite/blob/be559bea1b3aa38f4f6cdd54c5ba1c06276ccf1c/include/gsl/gsl-lite.hpp#L1410

I am using gsl-lite within a project that uses `-Wall -Wextra -Werror`, so when setting the contract level to off I cannot compile with those settings anymore.

I was thinking of creating a pull request with something like
```c++
    gsl_api gsl_constexpr14 span( std::nullptr_t, index_type
#if ! gsl_ELIDE_CONTRACT_EXPECTS
        size_in
#endif
    )
```
which does work, but seems a bit ugly. Maybe an `#if` `#else` `#endif` with two versions, the named and unnamed one would be better, although a bit repetitive.

**Comment by martinmoene** [comment]
Thank @kugelrund ,

Another way could be:
```
gsl_api gsl_constexpr14 span( std::nullptr_t, index_type gsl_EXPECTS_PARAM( size_in ) )
```
with
```
#if gsl_ELIDE_CONTRACT_EXPECTS
# define gsl_EXPECTS_PARAM( x )
#else
# define gsl_EXPECTS_PARAM( x )  x
#endif
```
but your suggestion if fine by me. It's easily changed later on if so desired.

**Comment by kugelrund** [comment]
Very nice way, i created a pull request based on it.
