### ISSUE TITLE
Reconsider name for gsl_EXPECTS_UNUSED_PARAM()

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/gsl-lite#125]
The beautifully numbered combination of PR #123 and issue #123 introduced macro `gsl_EXPECTS_UNUSED_PARAM(x)` that prevents an *unused parameter* warning in de case where `Expects(expr)` has been elided.

Perhaps the name can be improved upon while keeping it short. Depending on the configuration the indicated parameter *may* or *may not* be used and if used it is used by `Expects()` only.

1. `gsl_EXPECTS_UNUSED_PARAM(x)`, current: possibly suggesting the parameter is *unused unconditionally*.
2. `gsl_EXPECTS_PARAM(x)`, my initial idea: "it is a parameter for Expects()" (only).
3. `gsl_EXPECTS_ONLY_PARAM(x)`, 
4. ...

**Comment by mbeutel** [comment]
Note that `gsl_EXPECTS_UNUSED_PARAM()` was removed as part of https://github.com/martinmoene/gsl-lite/pull/172/commits/8526bd56adf1375a0037f6d9b51b639b693e2911 in PR #172. Unenforced contracts now use `decltype()` on the contract expression (if available) which suppresses the *unused parameter* warning.

Generally, *unused parameter* warnings can be avoided simply by casting the parameter to `void`, i.e.

```c++
void foo(int param)
{
    (void) param; // suppresses "unused parameter" warning
#ifdef USE_PARAM
    bar(param);
#endif // USE_PARAM
}
```

As far as I can tell this is a commonly understood idiom, so the comment shouldn't be necessary. There is no need to introduce macros like `gsl_UNUSED_IF_...()` which are necessarily specific to some configuration setting.

In C++17 we can also say

```c++
void foo([[maybe_unused]] int param)
{
#ifdef USE_PARAM
    bar(param);
#endif // USE_PARAM
}
```
cf. https://en.cppreference.com/w/cpp/language/attributes/maybe_unused.

**Comment by martinmoene** [comment]
Thanks for this explanation, referencing back to PR #172 and generally, your contributions :)
