### ISSUE TITLE
gsl::at doesn't work with const std::array

### ISSUE THREAD

**Issue by ilyalesokhin-starkware** [martinmoene/gsl-lite#132]
I'm getting the following error:
errror: binding value of type 'const std::array<unsigned long, 1>::value_type' (aka 'const unsigned long') to reference to type 'typename const array<unsigned long, 1>::value_type' (aka 'unsigned long') drops 'const' qualifier

     return cont[index];
  ]             ^~~~~~~~~~~
I'm compiling with clang6 with -std=gnu++14 

Possible solution:
-gsl_api inline gsl_constexpr14 typename Container::value_type & at( Container & cont, size_t index )
+gsl_api inline gsl_constexpr14 auto at(Container & cont, size_t index)->decltype(cont[0])

**Comment by mbeutel** [comment]
Addressed by https://github.com/martinmoene/gsl-lite/commit/39c37cef20bd79f85965f806e0a0c0efef8cf70f.
