### ISSUE TITLE
zstring_span and czstring_span

### ISSUE THREAD

**Issue by cbeck88** [martinmoene/gsl-lite#136]
The Microsoft GSL contains a special string span called `zstring_span` used to represent a string span known to have a null-terminator. This can be useful for interacting with legacy APIs, and avoiding use of raw pointers / calls to `::strlen` except at API boundary.

See "class basic_zstring_span`" and typedefs for `zstring_span` and `czstring_span`:
https://github.com/Microsoft/GSL/blob/master/include/gsl/string_span#L389

It appears to me that `gsl-lite` doesn't have these types -- is that intentional or merely an oversight? Would you accept a patch to provide them?

**Comment by martinmoene** [comment]
I might have simply missed the addition of `zstring_span` and siblings to M-GSL.

I'd welcome a PR to add these, preferably including test cases (and entry in the table under [Features](https://github.com/martinmoene/gsl-lite/blob/master/README.md#features)).

**Comment by martinmoene** [comment]
ToDo:

- Add tests
- Add entry in the table under [Features](https://github.com/martinmoene/gsl-lite/blob/master/README.md#features).

**Comment by martinmoene** [comment]
@cbeck88 Can this issue be closed?

**Comment by cbeck88** [comment]
thank you!

**Comment by cbeck88** [comment]
yes!
