### ISSUE TITLE
Add parentheses around min/max STL numerical_limits functions

### ISSUE THREAD

**Issue by ekcoh** [martinmoene/gsl-lite#140]
The std::numerical_limits macros when expressed as they currently are in source code will interfere with min/max macros if developing for Windows and have an include of <windows.h> preceeding gsl-lite include. There are some ways around this like trying to do undefs, or LEAN_MEAN, but the easiest and most reliable way is just to use parentheses around std calls, e.g. 

`
#line 2709
template< class T >
gsl_api inline span<T> ensure_z( T * const & sz, size_t max = std::numeric_limits<size_t>::max() )
{
    return details::ensure_sentinel<T, size_t, 0>( sz, max );
}
`

would be transformed into:

`
template< class T >
gsl_api inline span<T> ensure_z( T * const & sz, size_t max = (std::numeric_limits<size_t>::max)() )
{
    return details::ensure_sentinel<T, size_t, 0>( sz, max );
}
`

Or shortly, express _std::numeric_limits<size_t>::max()_ as _(std::numeric_limits<size_t>::max)()_ 
The problematic places can be found on #line 2685, 2709 in gsl-lite.hpp.

**Comment by martinmoene** [comment]
I think the intended way to suppress the definition of macros `min()` and `max()` from `windows.h` is `-DNOMINMAX`.

Parentheses around `std::numeric_limits<size_t>::max` have been added in https://github.com/martinmoene/gsl-lite/commit/119af9fcd3138cf0b7ee8f556cef884814b46095 in August 2018 as the result of [nonstd-lite issue 16](https://github.com/martinmoene/nonstd-lite-project/issues/16).

**Comment by ekcoh** [comment]
Thanks a lot for the info and the effort, guess I will try master instead of the 0.32 release then. Keep up the good work!

**Comment by martinmoene** [comment]
@ekcoh Releasing takes longer than usual, as I prefer to forgo that work  while working on the project [Improve coherence between lite projects](https://github.com/martinmoene/nonstd-lite-project/projects/1).
