### ISSUE TITLE
Add non-_TO_STD sibling macros

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/gsl-lite#141]
Add configuration flags to unconditionally control presence of constructors of the form `span(with_container_t, ...)` and functions `make_span()`, `byte_span()`.

Plan:
- [ ] Add gsl_FEATURE_WITH_CONTAINER
- [ ] Add gsl_FEATURE_MAKE_SPAN
- [ ] Add gsl_FEATURE_BYTE_SPAN
- [ ] Document gsl_FEATURE_WITH_CONTAINER
- [ ] Document gsl_FEATURE_MAKE_SPAN
- [ ] Document gsl_FEATURE_BYTE_SPAN
- [ ] Mention gsl_FEATURE_WITH_CONTAINER at gsl_FEATURE_WITH_CONTAINER_TO_STD
- [ ] Mention gsl_FEATURE_MAKE_SPAN at gsl_FEATURE_MAKE_SPAN_TO_STD
- [ ] Mention gsl_FEATURE_BYTE_SPAN at gsl_FEATURE_BYTE_SPAN_TO_STD

See span-lite issues [33](https://github.com/martinmoene/span-lite/issues/33), [34](https://github.com/martinmoene/span-lite/issues/34) and [32](https://github.com/martinmoene/span-lite/issues/32) .

**Comment by mbeutel** [comment]
Will be addressed by #181.
