### ISSUE TITLE
Add span::ssize(), ssize(span), size(span)

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/gsl-lite#144]
See [p1227, Signed ssize() functions, unsigned size() functions](http://wg21.link/p1227).

**Comment by mbeutel** [comment]
*gsl-lite* currently sort-of backports  C++17's [`size()`](https://en.cppreference.com/w/cpp/iterator/size) and [`data()`](https://en.cppreference.com/w/cpp/iterator/data). It also defines `ssize()` for `span<>`, but it does not yet implement a fully general [`ssize()`](https://en.cppreference.com/w/cpp/iterator/size) as proposed for C++20.
