### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by tadeu** [martinmoene/gsl-lite#145]
Hi! Thanks for this awesome library @martinmoene, it's very useful and convenient :)

I was using `gsl-lite` by just copying the header, but now I'm trying to improve the way it's used (since I'm using it in more places), so I created a `conda` package for it (the package manager that we use).  Now that I'm trying to use the packaged version, I've noticed that the last release is very old (0.32.0, from May 12, 2018), and I have compilation errors (for example, in Linux, building with GCC 5.4.0, it doesn't have `std::uncaught_exceptions()`, and this is already fixed in `master`).

So I'd like to know if there are plans for a new (0.33.0?) release (or if it could be released soon). Thanks!

**Comment by martinmoene** [comment]
@tadeu, Hope to make a release 'soon-ish' I've been working on overall improvements in [this *nonstd lite* project](https://github.com/martinmoene/nonstd-lite-project/projects/1).

**Comment by martinmoene** [comment]
@tadeu *gsl lite* v0.33.0has been released.

**Comment by tadeu** [comment]
Thanks :)
