### ISSUE TITLE
Confusing install directory of `gsl`

### ISSUE THREAD

**Issue by red1939** [martinmoene/gsl-lite#146]
By default `gsl-lite` installs itself into `lib/cmake/gsl/`. Issue with that is that if the top-most directory is selected (one that nests `lib`) for `CMAKE_PREFIX_PATH`, CMake will have troubles finding `.cmake` files as `gsl` directory is *not* `gsl-lite` thus it won't go deeper. This, non standard, behavior forces users to fiddle with `CMAKE_PREFIX_PATH`. Do we really need to pretend that we are gsl?

**Comment by martinmoene** [comment]
Thanks for your explanation, I wasn't aware of the consequence you describe.
There's perhaps no reason to not change the install folder to `gsl-lite`.

**Comment by red1939** [comment]
That almost works ;).

I can confirm that CMake now happily uses `lib/cmake/gsl-lite` as `gsl-lite_DIR`, so users don't have to go that deep to specify. Issue that is still left (please confirm that!), is that because of following lines in the `gsl-lite-targets.cmake`:

```
# Create imported target gsl::gsl-lite
add_library(gsl::gsl-lite INTERFACE IMPORTED)
```

We still use `gsl` as the namespace name. Following lines are to blame:

```
set( unit_name       "gsl" )
set( package_nspace  "gsl" )
```

I, personally, can live with that and just use `target_link_libraries(foo PRIVATE gsl::gsl-lite)`, but this is not aligned to what all examples/docs show. I think we need to get this straight.

**Comment by tadeu** [comment]
Just to let you know that it's working fine for me with the patch included here (https://github.com/martinmoene/gsl-lite/commit/df738cc388784308cef2d2f7ea4a2202a7e4c8ab), the only required change (from older versions) is to rename `gsl-lite::gsl-lite` in CMake files to `gsl::gsl-lite`.

**Comment by martinmoene** [comment]
Thanks @tadeu !
