### ISSUE TITLE
conan package outdated

### ISSUE THREAD

**Issue by lyro** [martinmoene/gsl-lite#148]
I'm using the `conan` package manager and it seems that (following the instructions in the README) the package is quite outdated (version 0.26 instead of 0.33).

**Comment by martinmoene** [comment]
It was updated to 0.33 a couple of days ago in df738cc388784308cef2d2f7ea4a2202a7e4c8ab, unfortunately just after the 0.33.0 release.

I intend to release all _lite_ projects in several days (a week?) as I'm concluding a substantial part of [nonstd-lite-project Improve coherence between lite projects](https://github.com/martinmoene/nonstd-lite-project/projects/1).

**Comment by lyro** [comment]
I see, i can wait ;)

 Thanks a lot.

**Comment by nathanaelg** [comment]
@martinmoene Any chance you can release `0.33` to conan, as is, in the mean time? Or even `0.32`?

**Comment by martinmoene** [comment]
[Released v0.34.0](https://github.com/martinmoene/gsl-lite/releases/tag/v0.34.0), [Conan package 0.34.0](https://bintray.com/martinmoene/nonstd-lite/gsl-lite%3Anonstd-lite/0.34.0%3Astable).
