### ISSUE TITLE
Should `gsl_FEATURE_IMPLICIT_MACRO` default to 0?

### ISSUE THREAD

**Issue by tadeu** [martinmoene/gsl-lite#156]
This is more of a doubt: I didn't find why there is an `implicit` macro in gsl-lite. The docs say that it's for symmetry with `explicit`, but is there a proposal for adding it to C++20? I also didn't find it in Microsoft GSL.

**Comment by martinmoene** [comment]
Can't find it the M-GSL source either, it _is_ mentioned in the [C++ Core Guidelines](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#main) though in section [GSL.util: Utilities](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#gslutil-utilities) and probably has its origin there:

    [[implicit]] // “Marker” to put on single-argument constructors to explicitly make them non-explicit

**Comment by tadeu** [comment]
Ah, nice, it is a marker. Having `implicit` in the global macro namespace seems a little bit too much (had a problem here in a piece of code because `implicit` was already a name being used), and I fixed it setting `gsl_FEATURE_IMPLICIT_MACRO=0` (awesome that there is this configuration).

Feel free to close the issue, it was just a suggestion, but it could also break other people code unnecessarily.

**Comment by martinmoene** [comment]
Thanks for bringing this up.

I'll change the default to `gsl_FEATURE_IMPLICIT_MACRO=0`, leaving the issue open for now.

**Comment by mbeutel** [comment]
Personally I'd prefer simply using `/*implicit*/` as a marker.

**Comment by mbeutel** [comment]
I'm closing this now; I think defaulting to off is the correct choice for an unprefixed lower-case macro, which is otherwise unnecessarily intrusive.
