### ISSUE TITLE
Semicolon in non-default Expects definition breaks some code

### ISSUE THREAD

**Issue by stohrendorf** [martinmoene/gsl-lite#160]
In https://github.com/martinmoene/gsl-lite/blob/master/include/gsl/gsl-lite.hpp#L741 and the following conditional definition of `Expects` (for `CONTRACT_VIOLATION_THROWS` and `CONTRACT_VIOLATION_CALLS_HANDLER`), the definitions have a semicolon, so you can't use it in the following example:
```
    if( getNode()->getChildren().empty() )
        Expects( !n["meshes"].IsDefined() );
    else
        Expects( !n["meshes"].IsDefined() || n["meshes"].size() <= getNode()->getChildren().size() );
```

**Comment by martinmoene** [comment]
Thanks @stohrendorf , this holds for lines 741, 743 (Expect) and 757, 759 (Ensures).

**Comment by stohrendorf** [comment]
Thanks :)
