### ISSUE TITLE
Add audit-level contract checks

### ISSUE THREAD

**Issue by mbeutel** [martinmoene/gsl-lite#168]
The contracts proposal (taken out of C++20 at the last minute) had a distinction between normal and "audit" checks. Example:

```c++
template <typename It> // assuming random-access iterators
auto median(It first, It last)
    [[ expects: first != last ]] // verifying that the range is not empty is cheap
    [[ expects audit: is_sorted(first, last) ]] // verifying that the range is sorted may be expensive
{
    return first[(last - first) / 2];
}
```

I think the idea was that there would be different levers for cheap and expensive checks.

Although "cheap" and "expensive" usually correlate with the "regular" and "audit" categories, I think the actual distinction between these categories should be "checks the compiler can reason about" and "checks which are opaque to the compiler". The first category would include all range or identity checks on scalar types. One would expect the compiler to understand that expressions in the first category are free of side-effects and can thus be elided if unnecessary. The second category would comprise all checks for which this doesn't necessarily hold, even if the checks are not expensive.

With such a distinction,  the compiler would be free to transform regular assertions into `__assume()` or similar optimizer-guiding intrinsics ([as Microsoft's GSL does](https://github.com/microsoft/GSL/blob/master/include/gsl/gsl_assert#L166)) when building with contracts unenforced, whereas audit-level assertions would simply be elided.

As far as I can see there is currently no way of expressing such semantics with either Microsoft's GSL or gsl-lite. In M-GSL `Expects()` either performs a check or forwards the expression to `GSL_ASSUME()`; there is no way to make it omit the check entirely. And when writing `GSL_ASSUME(potentially_expensive_function_call())` most compilers will generate code that actually calls the function:

https://gcc.godbolt.org/z/i015uU (GCC, Clang, ICC emit a call, only MSVC doesn't)

So audit-level contracts cannot really be expressed with M-GSL.

In gsl-lite we can define `gsl_CONFIG_CONTRACT_LEVEL_OFF` and have all contract checks elided entirely. However, there is no way of eliding only expensive checks, and there is no way to get `__assume()`-like intrinsics instead of unenforced contracts.

To resolve this, I propose the following extension:

- add macros `ExpectsAudit()` and `EnsuresAudit()` which expand to nothing by default
- add new contract level `gsl_CONFIG_CONTRACT_LEVEL_AUDIT` which enables both normal and audit-level checks (perhaps enabled by default if `NDEBUG` is not defined? not sure)
- add new contract level `gsl_CONFIG_CONTRACT_LEVEL_ASSUME` which compiles the `Expects()` and `Ensures()` into `__assume()`-like intrinsics à la `GSL_ASSUME()` and elides `ExpectsAudit()` and `EnsuresAudit()`

Would you consider this worth pursuing? If so, I'd be happy to provide a pull request.

**Comment by martinmoene** [comment]
Thanks for your interesting proposal and would like to include this in gsl-lite.
