### ISSUE TITLE
Separate span::index_type and index

### ISSUE THREAD

**Issue by paulromano** [martinmoene/gsl-lite#169]
In the C++20 draft, span::index_type is supposed to be size_t, as it is by default in gsl-lite. However, gsl-lite also uses the span index_type to set the type of `gsl::index`. The wording of the GSL regarding gsl::index makes it pretty clear that it is [supposed to be signed](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-subscripts). However, if you set `gsl_CONFIG_SPAN_INDEX_TYPE` to ptrdiff_t, this results in span using ptrdiff_t as its index_type, which then doesn't agree with the C++20 standard. Would it be possible to separate the types for `gsl::index` and `span::index_type`? Maybe add a `gsl_CONFIG_INDEX_TYPE` that is used specifically for `gsl::index`?

**Comment by martinmoene** [comment]
Will do.

Note to self: 
- Currently `index` is only used in span-related items.
- Update other functions to use [gsl::]index instead of `size_t`.

**Comment by mbeutel** [comment]
I plan to define `gsl::index = std::ptrdiff_t` for version 1.0 (ABI-breaking change). If desired we can also have an [ABI-breaking](#179) config option that switches it back to `size_t`.

**Comment by mbeutel** [comment]
Commit https://github.com/martinmoene/gsl-lite/commit/69eb1942ed550352ac45885fb55691f3817b81f4 now added `gsl_CONFIG_INDEX_TYPE` which controls the type of `gsl::index` independently of `gsl::span<>::index_type`.

This commit also adds the notion of *versioned defaults*: A set of defaults can be selected by setting the `gsl_CONFIG_DEFAULTS_VERSION` macro to 0 or 1, or by linking to CMake targets `gsl::gsl-lite-v0` or `gsl::gsl-lite-v1` which does the same thing. This is not yet documented; I intend to use this as a means for migration if we change the defaults for the next major version.

With `gsl_CONFIG_DEFAULTS_VERSION=1`, the new defaults are:

- `gsl_CONFIG_INDEX_TYPE` is `std::ptrdiff_t`
- `gsl_CONFIG_SPAN_INDEX_TYPE` is `std::size_t`
- `gsl_FEATURE_OWNER_MACRO` is 0
- `gsl_CONFIG_NOT_NULL_EXPLICIT_CTOR` is 1
- `gsl_CONFIG_TRANSPARENT_NOT_NULL` is 1
- `gsl_CONFIG_ALLOWS_NONSTRICT_SPAN_COMPARISON` is 0
