### ISSUE TITLE
Why is GSL_THROW_ON_CONTRACT_VIOLATION undefined?

### ISSUE THREAD

**Issue by ClausKlein** [martinmoene/gsl-lite#170]
This simple test program aborts:

```c++
// A span is a non-owning view over a contiguous sequence of objects, the
// storage of which is owned by some other object.

// TODO #define GSL_THROW_ON_CONTRACT_VIOLATION 1
#include <gsl/gsl-lite.hpp>

/***
Install the project...
/opt/local/bin/cmake -P cmake_install.cmake
-- Install configuration: "Debug"
-- Installing: /usr/local/lib/cmake/gsl-lite/gsl-lite-targets.cmake
-- Installing: /usr/local/lib/cmake/gsl-lite/gsl-lite-config.cmake
-- Installing: /usr/local/lib/cmake/gsl-lite/gsl-lite-config-version.cmake
-- Up-to-date: /usr/local/include
-- Installing: /usr/local/include/gsl
-- Installing: /usr/local/include/gsl/gsl
-- Installing: /usr/local/include/gsl/gsl-lite-vc6.hpp
-- Installing: /usr/local/include/gsl/gsl-lite.h
-- Installing: /usr/local/include/gsl/gsl-lite.hpp
-- Installing: /usr/local/include/gsl.h
-- Installing: /usr/local/include/gsl.hpp
Claus-MBP:build clausklein$
***/

#include <array>
#include <iostream>
#include <vector>

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

using gsl::at;
using gsl::span;

#ifndef GSL_THROW_ON_CONTRACT_VIOLATION
#define GSL_THROW_ON_CONTRACT_VIOLATION 1
#    warning missing GSL_THROW_ON_CONTRACT_VIOLATION defined!
#endif

TEST_CASE("at(): Terminates access to non-existing gsl::span elements")
{
    int arr[] = {1, 2, 3, 4};
    span<int> a(arr);

    CHECK(a.size() == 4);
    CHECK_THROWS_AS(at(a, 4), const std::exception &);
}
// FATAL ERROR: test case CRASHED: SIGABRT - Abort (abnormal termination) signal

TEST_CASE("at(): Terminates access to non-existing C-array elements")
{
    int a[4] = {1, 2, 3, 4};

    CHECK_THROWS_AS(at(a, 4), const std::exception &);
}
// FATAL ERROR: test case CRASHED: SIGABRT - Abort (abnormal termination) signal

TEST_CASE("at(): Terminates access to non-existing std::array elements (C++11)")
{
    std::array<int, 4> a{{1, 2, 3, 4}};

    CHECK(a.size() == 4);
    CHECK_THROWS_AS(a.at(4), const std::exception &);

    CHECK_THROWS_AS(at(a, 4), const std::exception &);
}
// FATAL ERROR: test case CRASHED: SIGABRT - Abort (abnormal termination) signal

TEST_CASE("at(): Terminates access to non-existing std::vector element (C++98)")
{
    std::vector<int> a{{1, 2, 3, 4}};

    CHECK(a.size() == 4);
    CHECK_THROWS_AS(a.at(4), const std::exception &);

    CHECK_THROWS_AS(at(a, 4), const std::exception &);
}
// FATAL ERROR: test case CRASHED: SIGABRT - Abort (abnormal termination) signal
```

**Comment by ClausKlein** [comment]
**The exception is not as useful as it should!**

**Q**: would it be possible to handle this with a **static_assert**()?

```
|| 2/2 Test #47: use_span .........................***Failed    0.02 sec
|| GSL: Precondition failure at /usr/local/include/gsl/gsl-lite.hpp:1895
```
```c++
int main(int argc, char *argv[])
{
    if (argc != 1) {
        std::cerr << "Usage: " << *argv << " <port>\n";
        return EXIT_FAILURE;
    }

    try {
        // XXX asio::io_context io_context;

        gsl::span<char *> args = {argv, 1};
        auto port = gsl::at(args, 1);   // BUG! <<<<<<<<<<<<<<<

        // XXX server s(io_context, std::strtol(port, NULL, 10));
        // XXX io_context.run();
    } catch (std::exception &e) {
        std::cout << e.what() << std::endl;
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
```

**Comment by mbeutel** [comment]
> ```c++
> #ifndef GSL_THROW_ON_CONTRACT_VIOLATION
> #define GSL_THROW_ON_CONTRACT_VIOLATION 1
> #    warning missing GSL_THROW_ON_CONTRACT_VIOLATION defined!
> #endif
> ```

`GSL_THROW_ON_CONTRACT_VIOLATION` (which is a compatibility alias for `gsl_CONFIG_CONTRACT_VIOLATION_THROWS`) is a build-time configuration option; it should be defined in the build system, not in source code. Example:

```cmake
cmake_minimum_required(VERSION 3.14)

# dependencies
find_package(gsl-lite REQUIRED)
find_package(doctest REQUIRED)

add_executable(test
    "test.cpp")

target_link_libraries(test
    PRIVATE
        gsl::gsl-lite
        doctest::doctest)

target_compile_definitions(test
    PRIVATE
        gsl_CONFIG_CONTRACT_VIOLATION_THROWS) # for testability, throw `gsl::fail_fast` on contract violation
```

**Comment by mbeutel** [comment]
> **The exception is not as useful as it should!**

Are you referring to the fact that the message references a location in gsl-lite.hpp and not in your source code?

A contract check expressed with `Expects()` produces an error message that references the source location of the `Expects()` call itself. This is possible because `Expects()` itself is a macro and can thus refer to `__FILE__` and `__LINE__`. However, `gsl::at()` is a function, and it does not have access to the source location of its caller.

You'll have to inspect the call stack of the `gsl::at()` invocation, which is best done with a debugger. I suppose *gsl-lite* could obtain a stack trace during construction of `gsl::fail_fast()` and include that in the exception message though.


> **Q**: would it be possible to handle this with a **static_assert**()?

Could you elaborate what exactly you want to be handled with `static_assert()`?

**Comment by ClausKlein** [comment]
```c++
        gsl::span<char *> args = {argv, 1};
        auto port = gal::at(args, 1);  
```

everything ist const and known at compile time, so it could by check with template code ...

**Comment by mbeutel** [comment]
> 
> 
> ```c++
>         gsl::span<char *> args = {argv, 1};
>         auto port = gal::at(args, 1);  
> ```
> 
> everything ist const and known at compile time, so it could by check with template code ...

This could be a compile-time failure if `argv`, `args`, and `port` were declared `constexpr` (and if *gsl-lite*'s support for `constexpr span<>` was a bit more thorough). But this is not possible without `constexpr`.

I'd be more than happy to be proven wrong about this, so please provide an example if you can.

**Comment by mbeutel** [comment]
I'm closing this issue because it's not actionable. I'd be happy to reopen if you have a suggestion how *gsl-lite* could detect the error in your snippet at compile time, but according to my knowledge of C++ this is not possible.
