### ISSUE TITLE
Decorate function signatures to support use in CUDA code

### ISSUE THREAD

**Issue by eyalroz** [martinmoene/gsl-lite#18]
When compiling GPU code using the [CUDA framework](http://www.nvidia.com/object/cuda_home_new.html), one needs to designate whether a function or a method is to be used on the "host" (the system's main CPU(s) and RAM) or on the "device" (the GPU card). This is done by prepending `__host__` and/or `__device__` to the declaration.

By default, code is host-only, thus gsl-lite cannot be used in GPU device code. However, it would be very easy (AFAICT) to make gsl-lite CUDA compatible:

```
#ifdef __CUDACC__
#define CUDA_DESIGNATOR __host__ __device__
#ifdef Expects
#undef Expects
#undef Ensures
#define Expects(x)
#define Ensures(x)
#endif
#else /* non-CUDA code */
#define CUDA_DESIGNATOR
#ifndef Expects
#define Expects(x)  ::gsl::fail_fast_assert((x))
#define Ensures(x)  ::gsl::fail_fast_assert((x))
#endif
#endif
```

and then prepending the function and member function definitions with `CUDA_DESIGNATOR`. It might even be the case that you don't need to get rid of the fail_fast_assert(), but I'm not sure about that.

There should be no impact on anything at all, i.e. this is a safe change.

I would very much like to see this committed (for use with my [DBMS-oriented CUDA kernel tester](https://bitbucket.org/eyalroz/kernel-tester/), which will soon be sporting a modified version version of gsl-lite as per the above.)

**Comment by martinmoene** [comment]
I have to think a moment about this. 

Perhaps something along the lines of the follwing:
```
// gsl-lite.h
#ifndef  Expects
...
#endif

#ifndef  Ensures
...
#endif

#ifndef  gsl_api
# define gsl_api
#endif

gsl_api inline void foo() { ... }
...
```
and compile with:
```
-DExpects="" -DEnsures="" -Dgsl_api=__DEVICE__
```

**Comment by eyalroz** [comment]
But that would require people using the gsl to have to actively set 
something, while my suggestion probably would not.

**Comment by martinmoene** [comment]
I'll try to combine your suggestion with the flexibility of still being able to define `gsl_api` etc. from the command line. Initially I'll leave `Expects` and `Ensures` alone.

**Comment by martinmoene** [comment]
Can you have alook at [release 0.4.0](https://github.com/martinmoene/gsl-lite/releases/tag/0.4.0) and let me know how it fares?

**Comment by eyalroz** [comment]
It will take me time, since I haven't integrated gsl-lite in my code. 
But I'll do this in the coming week.

**Comment by martinmoene** [comment]
Looking forward to it!

**Comment by martinmoene** [comment]
Made several other changes after compiling with nvcc via VS2012/CUDA 7.5.

**Comment by martinmoene** [comment]
@eyalroz Any news?

**Comment by eyalroz** [comment]
@martinmoene Sorry for disappearing on you. I'm testing it now... well, seems to work for my project - but it's small and doesn't use many of the GSL's features.

Anyway, there is an issue I should mention: You should not use ```__device__``` on functions which can't actually run as device code. Specifically, anything throwing an exception cannot run on the device, e.g.fail_fast_assert and anything calling fail_fast_assert cannot be device code. 

Consequently, I'm not sure it's a good idea to refer to ```__device__ __host__``` as ```gsl_api```.

**Comment by eyalroz** [comment]
Umm, ok, perhaps not "defined as nothing", but at least not throwing exceptions. Perhaps assert()'s would work.
