### ISSUE TITLE
Add gcc 4.7.3 to Travis CI configuration

### ISSUE THREAD

**Issue by petamas** [martinmoene/gsl-lite#186]
gcc 4.7.3 is an interesting beast: it already supports most of C++11, and is happy to define __cplusplus to 201103L when --std=c++11 is specified, but it lacks a few features, like rvalue references for *this or inheriting constructors. Also, we use it at my workplace on a few projects, so it's important for us that GSL-Lite works with it. :)

Full list of supported/unsupported features here: https://gcc.gnu.org/gcc-4.7/cxx0x_status.html

**Comment by mbeutel** [comment]
Implemented by https://github.com/martinmoene/gsl-lite/commit/9c926da39264adb64cf6ff72ddeb41e3fdc8b7b4.
