### ISSUE TITLE
Warning in testAssume()

### ISSUE THREAD

**Issue by petamas** [martinmoene/gsl-lite#195]
There's this function is asserts.t.cpp:

```
int testAssume( int i, std::vector<int> const& v )
{
    // This should compile without warnings.
    gsl_ASSUME( i >= 0 && static_cast<std::size_t>(i) < v.size() );
    return v.at( i );
}
```

Despite the comment, the return statement generates a warning ("conversion from unsigned to signed int", however it is phrased in different compilers).

The warning itself is pretty easy to fix (just add static_cast, duh), but the comment worries me: is v.at() supposed to handle a signed argument? Or does the comment talk about another warning? (Also, why aren't warnings treated as errors in the Travis builds to catch these things early?)

**Comment by mbeutel** [comment]
> The warning itself is pretty easy to fix (just add static_cast, duh), but the comment worries me: is v.at() supposed to handle a signed argument? Or does the comment talk about another warning?

The test was added in commit https://github.com/martinmoene/gsl-lite/commit/97fb51f782afb5df2618a8fa2941ec9807a6f86b which explains it:

>  ### Use `__builtin_unreachable()` instead of `__builtin_assume()` for Clang
>
> `__builtin_assume()` warns about possible side effects (cf.
https://github.com/microsoft/clang/blob/master/test/Sema/builtin-assume.c),
which is generally helpful, but the warning is produced even if the
optimizer will later inline the expression and find it free of side-
effects, cf. https://gcc.godbolt.org/z/ZcKfbp .

The comment should have conveyed this information too; I'll add it with my next PR (and also the missing `static_cast<>()`; thanks for pointing it out).


> (Also, why aren't warnings treated as errors in the Travis builds to catch these things early?)

I agree that this is something we should do. I plan to look at CI soon (something I'm not very experienced with), to add more configurations (e.g. VS 2019), and also to make warnings build-breaking.

**Comment by petamas** [comment]
Thanks for the answer! The comment referring to another warning was my first guess, but I wanted to make sure. :) I also do not have much experience with Travis and AppVeyor (we use TeamCity and custom build scripts), but they seem nicely configurable, and easy to use systems.

**Comment by mbeutel** [comment]
Comment was added in https://github.com/martinmoene/gsl-lite/commit/b81d806aeddc9d4b0c475241f92135e35b283b8b (PR #202).
