### ISSUE TITLE
Introduce make_not_null

### ISSUE THREAD

**Issue by petamas** [martinmoene/gsl-lite#200]
I know it's 2019 and deduction guides are all the rage, but it would be real nice for pre-C++17 guys like me to not have to specify what kind of not_null we'd like to create from a pointer, like with make_pair, make_tuple, etc.

**Comment by mbeutel** [comment]
Sure, I can add `make_not_null<>()` with my next PR.

[I'll be away for one week now.]

**Comment by petamas** [comment]
I'm happy to provide a PR, I just wanted to verify if it's a good idea. :)

**Comment by mbeutel** [comment]
I think it is almost a necessity because it is the conventional C++14 analogon of the deduction guide. M-GSL has it too, so it could also be motivated with compatibility concerns.

I did hesitate because the naming looks funny in this case, e.g. `make_not_null(nullptr)`. Perhaps calling it `check_not_null()` would be a better choice, though clearly a less conventional one.

**Comment by petamas** [comment]
I did not see they have a version in M-GSL - in this case, I think it's an absolute must-have for us!

I don't understand what you mean by make_not_null(nullptr) - that should be a deleted overload.

In other situations, I understand one might see make_not_null and think it somehow turns a null pointer into a non-null pointer, but I think it is a low risk, as make_XXX is a pretty standard name. Also, we could argue the same about not_null's constructor - from this point of view, Dropbox nn's approach is much safer:
- it does not have an nn(T) constructor
- it does have an i_promise_i_checked_for_null_t tag type
- it does have an nn(i_promise_i_checked_for_null_t, T) constructor
- you're urged to create some macro named NN_CHECK (or any name you want to use, like CHECK_NOT_NULL), which checks for null, does whatever error handling you want to if the pointer is null, then calls the tagged constructor

This way, you must be pretty explicit about creating nn objects, but I think it's not much safer to use that version than ours (only advantage is that you can't construct an nn "by accident", using static_casts and such).

All in all, I think make_not_null is the name we should use in the library (naturally, consumers are free to add a new name for it, if they want).

**Comment by mbeutel** [comment]
PR #202 adds `make_not_null<>()` (https://github.com/martinmoene/gsl-lite/commit/042d4749891ccac2deca844d9d331b44c7b47e2d) and deduction guides (https://github.com/martinmoene/gsl-lite/commit/7a6278305c8ff644736c5d798bc5591dc15e5051).
