### ISSUE TITLE
Visual Studio 2015 Update 3 missing _HAS_CPP0X

### ISSUE THREAD

**Issue by exjam** [martinmoene/gsl-lite#21]
Visual Studio 2015 Update 3  seems to no longer have _HAS_CPP0X defined, this affects:
define gsl_HAVE_CONTAINER_DATA_METHOD  1
define gsl_HAVE_SHARED_PTR  1
define gsl_HAVE_UNIQUE_PTR  1

I did the following change on my fork but I wasn't sure if it was the right way to fix it, so I created an issue instead of a PR for this one. Wasn't sure if you'd prefer to move them up into the ifdef gsl_COMPILER_MSVC_VERSION >= 14 block above.

https://github.com/decaf-emu/gsl-lite/commit/a9efb2dfce8411a1a36049e3a3b9e06d0020a9aa

**Comment by martinmoene** [comment]
Thanks James!

I following your suggestion (be it I ordered the compiler versions new-old). I didn't move the gsl_HAVE_... macros to the "block above" as that handles compiler, not library capabilities.
