### ISSUE TITLE
Do not allow implicit construction of not_null from not implicitly convertible types

### ISSUE THREAD

**Issue by stohrendorf** [martinmoene/gsl-lite#210]
I have disabled explicit construction of `not_null` in my code and found a problem handling conversion of pointer types.

Consider this:
```cpp
void foo(const not_null<shared_ptr<Bar>>&);
Bar* errorPtr = ...;
foo(errorPtr); // implicitly constructs shared_ptr
```

That is, only allow implicit construction of a `not_null<T>` from `U` if `T` is implicitly convertible from `U`. A possible solution to this is here: https://stackoverflow.com/a/42787839.

**Comment by mbeutel** [comment]
Thank you; indeed there were some issues in the converting constructor of `not_null<>`.

#211 should fix the conversion issues and also [adds some tests](https://github.com/martinmoene/gsl-lite/pull/211/files#diff-5e8cbca636c91b96c5aa52e6feedd759) for your scenario. It might need a few more iterations before it passes through our test suite of historical compilers though.

**Comment by martinmoene** [comment]
Pet peeve ahead :)

> #211 should fix the conversion issues and also adds some tests for your scenario.

`// We should permit conversion to underlying type.`

I'd like to suggest:

`// Permit conversion to underlying type.`

i.e. either the code permits (success) or it does not (unintended failure to meet requirement).

Ref.: Structure and Interpretation of Test Cases - Kevlin Henney, Apr 2, 2019, NDC Conferences

https://youtu.be/tWn8RA_DEic?t=1605

**Comment by mbeutel** [comment]
Comments updated, thanks :)

**Comment by stohrendorf** [comment]
Thank you!
