### ISSUE TITLE
Can't create span<const T> from non-const T*

### ISSUE THREAD

**Issue by marton78** [martinmoene/gsl-lite#22]
Hi,

the following fails to compile:

```c++
uint8_t* p;
size_t n;
gsl::span<const uint8_t> s(p, n);
```

The workaround is to first construct a `span<T>`, which is implicitly convertible to a `span<const T>`.

**Comment by martinmoene** [comment]
Thanks! Fixed in [release 0.7.3](https://github.com/martinmoene/gsl-lite/releases/tag/v0.7.3).

**Comment by martinmoene** [comment]
Apparently to prevent ambiguous constructors. It came with Microsoft's GSL code.
