### ISSUE TITLE
Hook up Azure Pipelines; consolidate CI

### ISSUE THREAD

**Issue by mbeutel** [martinmoene/gsl-lite#227]
As of commit https://github.com/martinmoene/gsl-lite/commit/20225d0c0ed7d24b5d44123632bf28f36cc8b013 (PR #225) *gsl-lite* now has configuration scripts for three CI providers:

- [**Azure Pipelines**](https://dev.azure.com/moritzbeutel/gsl-lite/_build/results?buildId=367&view=results):
  - takes ~12min to run (10 concurrent jobs)
  - tests only Debug builds
  - tests GCC 5 through 9 on Linux
  - tests Clang 4 through 9 on Linux
  - tests MSVC 16 through 19.2 on Windows
  - tests NVCC 10.2 on Windows and Linux
  - tests GCC 6 through 9 on MacOS
  - tests AppleClang 8.1, 9, 9.1, 10, 10.0.1, and 11 on MacOS
  - tests GCC and Clang with AddressSanitizer and UndefinedBehaviorSanitizer on Linux

- [**AppVeyor:**](https://ci.appveyor.com/project/martinmoene/gsl-lite/builds/30083763)
  - takes ~1h 10min to run (sequential jobs)
  - tests both Debug and Release builds
  - tests MSVC 16 through 19.2 on Windows

- [**Travis:**](https://travis-ci.org/martinmoene/gsl-lite/builds/636523495)
  - takes ~16min to run (3 concurrent jobs)
  - tests with no build configuration
  - tests GCC 4.7, 4.8, 4.9, and 5 through 8 on Linux
  - tests Clang 3.5, 3.6, 3.7, 3.8, 3.9, and 4 through 6 on Linux
  - tests AppleClang 7.3, 8, 9, 10, 10.0.1, and 11 on MacOS
  
Azure pipelines currently isn't hooked up to this repository, so it won't run automatically.

I tried adding a pipeline for this repo but I get this error message: "Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository." So apparently being a collaborator isn't sufficient.

@martinmoene, could you perhaps help me again there and set up a pipeline for *gsl-lite* at https://dev.azure.com/? Azure should find the correct pipeline definition automatically after you select the *gsl-lite* GitHub repository.

After this is done, the redundant CI runs should be consolidated to reduce the overall duration of CI so we can iterate faster. In particular, we should probably remove VS 2017 and VS 2019 builds in AppVeyor, some of the newer GCC, Clang, and Xcode versions in Travis, and the VS 2010, 2012, 2013 builds in Azure Pipelines.

**Comment by martinmoene** [comment]
@mbeutel , i have set up a pipeline for gsl-lite at https://dev.azure.com/

don't know anything about it; trying to run yields: 

> Repository templates references endpoint mbeutel which does not exist or is not authorized for use

**Comment by mbeutel** [comment]
Thank you! I changed the service connection, which fixed that particular issue. Here's the next:

> A task is missing. The pipeline references a task called 'run-cmake'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com.

This is the task I'm using in [my job template](https://github.com/mbeutel/CImakeshift/blob/master/azure-pipelines-job-cmake.yml):

https://marketplace.visualstudio.com/items?itemName=lucappa.cmake-ninja-vcpkg-tasks

Could you perhaps install that too?

**Comment by martinmoene** [comment]
mm, i've added you as an administrator to the Azure *gsl lite* project, perhaps that is easier for you. At any rate it was easier for me :)

**Comment by martinmoene** [comment]
Ok, installed lucappa.cmake-ninja-vcpkg-tasks.

**Comment by martinmoene** [comment]
And started a run...

**Comment by mbeutel** [comment]
It works :) Thank you! And sorry for bothering you with this.

I'll go add some status badges and update the readme.

**Comment by martinmoene** [comment]
you're welcome, my task wasn't that difficult in the end :)

**Comment by mbeutel** [comment]
Unfortunately Travis is a bit flaky; [this job](https://travis-ci.org/martinmoene/gsl-lite/jobs/636612964) failed, but I've seen similar failures in the past, and they all went away after restarting the job manually :(

**Comment by mbeutel** [comment]
With PR #230 we now have:

- [**Azure Pipelines**](https://dev.azure.com/martinmoene/gsl-lite/_build/results?buildId=7&view=results):
  - takes 7-8min to run (10 concurrent jobs)
  - tests only Debug builds
  - tests GCC 6 through 9 on Linux
  - tests Clang 4 through 9 on Linux
  - tests MSVC 19.1 and 19.2 on Windows
  - tests NVCC 10.2 on Windows and Linux
  - tests GCC 6 through 9 on MacOS
  - tests AppleClang 8.1, 9, 9.1, 10, 10.0.1, and 11 on MacOS
  - tests GCC and Clang with AddressSanitizer and UndefinedBehaviorSanitizer on Linux

- [**AppVeyor:**](https://ci.appveyor.com/project/martinmoene/gsl-lite/builds/30088633)
  - takes 8-9min to run (sequential jobs)
  - tests only Debug builds
  - tests MSVC 16 through 19 on Windows

- [**Travis:**](https://travis-ci.org/martinmoene/gsl-lite/builds/636621709)
  - takes 5-6min to run (3 concurrent jobs)
  - tests with no build configuration
  - tests GCC 4.7, 4.8, 4.9, and 5 on Linux
  - tests Clang 3.5, 3.6, 3.7, 3.8, and 3.9 on Linux
  - tests AppleClang 7.3 and 8 on MacOS
