### ISSUE TITLE
Difference between `span<const T>` and `const span<T>`

### ISSUE THREAD

**Issue by marton78** [martinmoene/gsl-lite#23]
Hi,

currently, writing to a `const span<T>` doesn't compile:

```c++
int* p;
size_t n;
const span<int> s(p, n);

s[0] = 42; // doesn't compile
```

This is surprising behaviour, and not what Microsoft's GSL implementation does -- or the STL, for that matter. In the STL, it is customary that constness is shallow, that is:

```c++
const std::shared_ptr<int> p = std::make_shared<int>(42);
*p = 43; // this is fine
p = std::make_shared<int>(44); // this isn't
```

```c++
std::shared_ptr<const int> p = std::make_shared<int>(42);
*p = 43; // this doesn't compile
p = std::make_shared<int>(44); // this does!
```

Shouldn't GSL adhere to this principle?

**Comment by martinmoene** [comment]
Sure, thanks! Fixed in [release 0.7.3](https://github.com/martinmoene/gsl-lite/releases/tag/v0.7.3).
