### ISSUE TITLE
Wrong boundary check in subspan

### ISSUE THREAD

**Issue by yachoor** [martinmoene/gsl-lite#25]
It seems that with Microsoft GSL it is possible to create empty subspan by giving `offset == length()`:
```c++
int arr[5] = {1, 2, 3, 4, 5};
span<int, 5> av = arr;
CHECK(av.subspan(5).length() == 0);
CHECK_THROW(av.subspan(6).length(), fail_fast);
```
but with gsl-lite it's an error (blow_offset test case).

**Comment by martinmoene** [comment]
Merged PR #26. Thanks to @yachoor.
