### ISSUE TITLE
Unexpected results from compare operators.

### ISSUE THREAD

**Issue by yachoor** [martinmoene/gsl-lite#32]
After span's comparison functions have been made free functions in release 0.9.0, they now give incorrect results when comparing spans differing in constness:
```C++
char data[] = {'a', 'b'};
gsl::string_span a = gsl::as_span(data);
gsl::cstring_span b = gsl::as_span(data).last(1);

assert(a != b); // previously worked as expected, now converts to bool and compares equal!
```

**Comment by martinmoene** [comment]
Resolved by issue #33 and commit 53dfc40d70e04783538deebeef908587e4530a95:

[Allow comparison of spans only differing in cv-ness](53dfc40d70e04783538deebeef908587e4530a95)

Note: The C++ standard does not allow to compare containers that only differ in cv-ness.

This also holds for M-GSL. However M-GSL does allow to compare string_span with cstring_span.

The comparation of string_span in GSL Lite (as it is now) is the same as that of span.
To continue allowing to compare string_span with cstring_span in GSL Lite, it is now possible to compare spans differing in cv-ness.

Perhaps a configuration flag that allows to switch between this behavior and the strict behavior is in order.
