### ISSUE TITLE
Make operator X=(byte&, ...) compatible with C++11 constexpr rules

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/gsl-lite#37]
See M-GSL PR # 369.

E.g., change
```
template<...>
gsl_api inline gsl_constexpr14 byte & operator>>=( byte & b,... ) gsl_noexcept
{
    ...
    b.v = to_uchar( b ) >> shift; return b;
}
```
to

```
template<...>
gsl_api inline gsl_constexpr byte & operator>>=( byte & b,... ) gsl_noexcept
{
    ...
    return b.v = to_uchar( b ) >> shift, b;
}
```

**Comment by martinmoene** [comment]
To my knowledge, the assignment `b.v = ...` cannot be constexpr in C++11.

**Comment by MikeGitb** [comment]
@martinmoene: I think you are right. I should have mentioned that in the MS-GSL PR. I initially chose that somewhat weird syntax, to satisfy the c++11 requirement to only have a single statement in the body, but when I remembered that the MS-GSL doesn't support c++11 anyway I didn't actually pursue c++11 constexpr compatibility any further.
