### ISSUE TITLE
Invalid conversion allowed in gsl::span constructor

### ISSUE THREAD

**Issue by prog-fh** [martinmoene/gsl-lite#41]
The constructor for gsl::span from any container seems to be a bit too permissive when it comes to Base and Derived types. (nb: the same remark applies to Microsoft's version of GSL)

```
struct B { int _b; B(int b) : _b{b} { } }; 
struct D : B { int _d; D(int b,int d) : B{b}, _d{d} { } };
std::vector<D> v1={{1,10},{2,20},{3,30}};
gsl::span<B> s1(v1);
for(const auto &i: s1) { std::cerr << i._b << ' '; } std::cerr << '\n';
// obtained: 1 10 2 20 3 30 (i.e. kind of reinterpret_cast with an incorrect size!)
// expected: compilation failure since D[] is not convertible to B[]
//           (although D* is convertible to B*)
```

I would suggest a constructor similar to this one.

```
  template<typename Container,
           typename PointerType = decltype(std::declval<Container>().data()),
           typename ValueType = decltype(*std::declval<PointerType>()),
           typename SizeType = decltype(std::declval<Container>().size()),
           typename = std::enable_if_t<
                        std::is_convertible<PointerType,pointer>::value&&
                        std::is_same<std::decay_t<ValueType>,
                                     std::decay_t<value_type>>::value&&
                        std::is_convertible<SizeType,size_type>::value>>
  gsl_api gsl_constexpr14
  span(Container &c) noexcept
  : begin_{c.data()}
  , end_{c.data()+c.size()}
  { }

```

By the way (another topic): shouldn't  GSL_UNENFORCED_ON_CONTRACT_VIOLATION be automatically defined when NDEBUG is?

Thank you for your great work (and readable code!).
Hope that helps.

**Comment by martinmoene** [comment]
Thanks!

To answer your question right away:

>By the way (another topic): shouldn't GSL_UNENFORCED_ON_CONTRACT_VIOLATION be automatically defined when NDEBUG is?

Boundary checking at runtime at default is by intent, see [this comment](https://github.com/martinmoene/gsl-lite/issues/24#issuecomment-231723362).

**Comment by martinmoene** [comment]
M-GSL [issue #384](https://github.com/Microsoft/GSL/issues/384).

**Comment by martinmoene** [comment]
Closing this as the constructor for containers is constrained as in proposal [p0122](http://wg21.link/p0122), see [release 0.31.0](https://github.com/martinmoene/gsl-lite/releases/tag/v0.31.0).
