### ISSUE TITLE
add gsl.h to include?

### ISSUE THREAD

**Issue by rkhlebnikov** [martinmoene/gsl-lite#5]
Hi, I am using GSL in my multi-platform CMake-based project (MSVS2013 + GCC 4.9). Unfortunately I cannot switch to GCC 5+ at the moment, so I will use gsl-lite when building under Linux. I set up GSL as a CMake external project and to avoid any ifdefs, I just added a `gsl.h` to the include folder in my fork which simply includes `gsl/gsl-lite.h` internally. Does it make sense to you to have such a file in gsl-lite? If yes, I'll make a PR or you can simply add it yourself.

**Comment by rkhlebnikov** [comment]
It seems it's a bit more involved than that :) E.g. when using GSL I write `gsl::cstring_span<>` whereas in gsl-lite, I need to use `gsl::cstring_span`. This would require adding a dummy template parameter to `span` with default value. I'll do the work to allow using the same syntax using gsl-lite as it would be with GSL - let me know if you're interested.

**Comment by martinmoene** [comment]
Hi, I've added `include/gsl.h`.

I was aware of the `gsl::Xstring_span` template/non-template difference. I didn't like writing `gsl::cstring_span<> a_span`, never specifying a template parameter very much. 

Although I based gsl-lite on MS GSL, that just is *a* implementation of GSL which also still in flux. Further, we've yet to see a specification for GSL. 

I see your point of compatibility, but I'm *not yet* sure if I'd change to the templated version.

**Comment by rkhlebnikov** [comment]
Good point. Well, I'll keep it in my fork then, at least for now - this is for my project after all and GSL is under very active development at the moment. Adding the dummy parameter was very easy, but supporting that without alias templates will be terribly ugly. I'll give it a go anyway even though I don't need it as gcc 4.9.2 supports alias templates. I'll let you know when/if it is working so you can make an informed decision.

**Comment by rkhlebnikov** [comment]
It seems like without alias templates this would become an unmaintainable hell, so I'll just keep my fork which will only work for the case I need (i.e. with alias templates) and it seems to make no sense to pull these changes in your repo. Thanks for your effort! I'll close the issue now.

**Comment by martinmoene** [comment]
Thanks for your interest & suggestions!
