### ISSUE TITLE
Specialize std::hash for gsl::byte

### ISSUE THREAD

**Issue by KazDragon** [martinmoene/gsl-lite#51]
This would allow you to use gsl::byte as a key in an unordered_map.

**Comment by martinmoene** [comment]
Added in v0.14.0

**Comment by KazDragon** [comment]
Wow, I just came by to edit my text to make it less demanding and also to thank you for this library, but it's already done.  Awesome.  Thanks!

**Comment by martinmoene** [comment]
You're welcome :)
