### ISSUE TITLE
as_bytes for basic_string_span

### ISSUE THREAD

**Issue by Sillamacka** [martinmoene/gsl-lite#62]
Hello,

I think it would be convenient to be able to use `as_bytes` on `basic_string_span`, I just had a need for this in my project.

What do you think of this? [Here is the diff](https://gist.github.com/Sillamacka/55396c0ecd6c4cbbbfa9baa5f43fe1e1)

Thanks!

**Comment by martinmoene** [comment]
Thanks Magnus,

Added it to [release 0.21.0](https://github.com/martinmoene/gsl-lite/releases/tag/v0.21.0).

Regards,
Martin
