### ISSUE TITLE
Does not compile with -Werror and -Wundef set

### ISSUE THREAD

**Issue by minielim** [martinmoene/gsl-lite#74]
While attempting updates to support this warning flag configuration use in our build, it was found that nothing defines gsl_CONFIG_CONTRACT_VIOLATION_TERMINATES yet it is used in the defining of gsl_CONFIG_CONTRACT_VIOLATION_THROWS_V.

**Comment by martinmoene** [comment]
However, `gsl_CONFIG_CONTRACT_VIOLATION_TERMINATES` is only used in `defined(...)` and I do not see it reported due to `-Wundef` with g++ (GCC) 5.2.0 on Windows.

I _can_ see lots of other cases related to `-Wundef` though.

**Comment by martinmoene** [comment]
In [release 0.23.0](https://github.com/martinmoene/gsl-lite/releases/tag/v0.23.0).
