### ISSUE TITLE
Implement to_byte() using conversion from underlying type.

### ISSUE THREAD

**Issue by cinghiale** [martinmoene/gsl-lite#75]
Hi,

simply including the gsl-lite header with gcc 7.1 and c++17 enabled result in the above error.

I know too little of gsl-lite to understand all the implications, but can be this a valid workaround?

```diff
template< class T >
gsl_api inline gsl_constexpr byte to_byte( T v ) gsl_noexcept
{
#if    gsl_HAVE_ENUM_CLASS_CONSTRUCTION_FROM_UNDERLYING_TYPE
-    static_assert( false, "Implement to_byte() using conversion from underlying type." );
+    return static_cast<byte>(v);
#elif  gsl_HAVE_CONSTEXPR_11
    return { static_cast<typename byte::type>( v ) };
#else
    byte b = { static_cast<typename byte::type>( v ) }; return b;
#endif
}
```

**Comment by martinmoene** [comment]
Thanks for pointing out. IIRC the static_assert is there because I couldn't test it at the time.

In addtion [line 956](https://github.com/martinmoene/gsl-lite/blob/0ab6d14ce5092378e068ac3c18d54abe22cf14fc/include/gsl/gsl-lite.h#L956) needs to change to:
```
    return static_cast<typename std::underlying_type<byte>::type>( b );
```

**Comment by cinghiale** [comment]
do you like a mini PR for this change?

**Comment by martinmoene** [comment]
Not really necessary, but appreciated if you do.

**Comment by martinmoene** [comment]
In [release 0.24.0](https://github.com/martinmoene/gsl-lite/releases/tag/v0.24.0).
