### ISSUE TITLE
Add not_null comparison operators for raw pointers 

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/gsl-lite#78]
See [M-GSL PR 558](https://github.com/Microsoft/GSL/pull/558).

**Comment by martinmoene** [comment]
Questionable.

**Comment by mbeutel** [comment]
This should be covered by the [generic SFINAE-guarded comparison operators](https://github.com/martinmoene/gsl-lite/blob/8bbe0fb9e975ba26d97b2b66165b6195d424cb58/include/gsl/gsl-lite.hpp#L1904..L2016) we now define, modulo any compiler bugs I'm unaware of.
