### ISSUE TITLE
Is comparing empty span-s (string_span-s) legal, do they compare equal?

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/gsl-lite#96]
Find specification to decide if `span<int>() == span<int>()` must be allowed.

**Comment by mbeutel** [comment]
C++20 spans are not comparable at all, cf. https://en.cppreference.com/w/cpp/container/span.

I think this is the right thing to do. Spans have reference semantics and hence shallow copy: copying a span only copies the pointer and not the underlying data. So doing a deep comparison would be inconsistent and lead to surprising behavior. On the other hand, having a shallow comparison would lead to unexpected behavior in cases such as

```c++
template <typename R>
    void foo(R&& r1, R&& r2)
{
    if (r1 != r2)
    {
        bar(r1, r2);
    }
}
```

where `foo(vector1, vector1)` would behave differently from `foo(make_span(vector1), make_span(vector2))`.

Cf. http://wg21.link/P1085 for a thorough discussion of the issues.
